### ISSUE TITLE
String interpolation / for comprehension: illegal position span

### ISSUE THREAD

**Issue by Sciss** [dotterweide/dotterweide#21]
In this example
```scala
for {
  i <- self.attr.$[IntObj]("int")
} {
  println(s"Value is $|i")
}
```
with cursor represented by `|`, typing the opening brace `{` yields:

```
java.lang.IllegalArgumentException: Invalid substring range
	at java.text.AttributedString.addAttribute(AttributedString.java:350)
	at dotterweide.editor.Attributes.decorate(Text.scala:25)
	at dotterweide.editor.painter.TextPainter$.$anonfun$render$1(TextPainter.scala:149)
	at dotterweide.editor.painter.TextPainter$.$anonfun$render$1$adapted(TextPainter.scala:146)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at dotterweide.editor.painter.TextPainter$.dotterweide$editor$painter$TextPainter$$render(TextPainter.scala:146)
...
```

**Comment by Sciss** [comment]
Self contained case:

```scala
val to = Option("foo")
for {
  t <- to
} {
  println(s"length $|t")
}
```
Now press `{`

**Comment by Sciss** [comment]
It comes from the tokens, so scalariform, with an empty span (start == end) which is forbidden by attributed string.
